version: '3.8'
services:
  autoparte:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - redis
  redis:
    image: redis:latest
    ports:
      - 6379:6379
